package notiflight.GUI;
import java.awt.FlowLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import notiflight.Classes.EmailNotification;
import notiflight.Classes.FlightChange;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GJKOfficial
 */
public class Notify extends javax.swing.JFrame {

    /**
     * Creates new form Notify
     */
    public Notify() {
        initComponents();
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jTextField1.setEnabled(false);
        jComboBox1.setEnabled(false);
        groupButton();
        
    }
    private void groupButton( ) {

        ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(jRadioButton1);
        bg1.add(jRadioButton2);
        bg1.add(jRadioButton3);
        bg1.add(jRadioButton4);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jRadioButton1.setText("1 minute");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("10 minutes");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("1 hour");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Enable Flight Notifications");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Custom interval");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Checking Intervals:");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "minutes", "hours"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jLabel1))
                        .addGap(161, 161, 161))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(522, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:

        if(jCheckBox1.isSelected()==true) {
            
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton4.setEnabled(true);
        }
        
        if(jCheckBox1.isSelected()==false) {
            
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jTextField1.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jTextField1.setEnabled(false);
        jComboBox1.setEnabled(false);        
        //loop to check for changes every 1 minute
        
        Thread thread = new Thread(new Runnable() {
            public void run() {
                while(true) {
                    try {
                        FlightChange.check();
                    } catch (Exception ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
           
                    try {
                        //Time Interval
                        Thread.sleep(60 * 1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        FlightChange.check2();
                    } catch (Exception ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                String doc1 = "/Users/GJKOfficial/NotiFlight/Downloaded/DownloadedSchedule.txt";
                String doc2 = "/Users/GJKOfficial/NotiFlight/Downloaded/DownloadedSchedule2.txt";
                
                try {
                    if (!FlightChange.checkEqual(doc1, doc2)) {
                        EmailNotification.Email();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            });
            thread.start();
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            Menu Info = new Menu();
            Info.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jComboBox1.setEnabled(false);        
        jTextField1.setEnabled(false);
        Thread thread = new Thread(new Runnable() {

            public void run() {
                
                while(true) {
                    try {
                        FlightChange.check();
                    } catch (Exception ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
           
                    try {
                        //Time Interval
                        Thread.sleep(600 * 1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        FlightChange.check2();
                    } catch (Exception ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                String doc1 = "/Users/GJKOfficial/NotiFlight/Downloaded/DownloadedSchedule.txt";
                String doc2 = "/Users/GJKOfficial/NotiFlight/Downloaded/DownloadedSchedule2.txt";
                
                try {
                    if (!FlightChange.checkEqual(doc1, doc2)) {
                        EmailNotification.Email();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            });
            thread.start();
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jTextField1.setEnabled(false);
        jComboBox1.setEnabled(false);
        Thread thread = new Thread(new Runnable() {

            public void run() {
                
                while(true) {
                    try {
                        FlightChange.check();
                    } catch (Exception ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
           
                    try {
                        //Time Interval
                        Thread.sleep(3600 * 1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        FlightChange.check2();
                    } catch (Exception ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                String doc1 = "/Users/GJKOfficial/NotiFlight/Downloaded/DownloadedSchedule.txt";
                String doc2 = "/Users/GJKOfficial/NotiFlight/Downloaded/DownloadedSchedule2.txt";
                
                try {
                    if (!FlightChange.checkEqual(doc1, doc2)) {
                        EmailNotification.Email();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            });
            thread.start();
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton4.isSelected()) {
            jTextField1.setEnabled(true);
            jComboBox1.setEnabled(true);
        }
        
        if (!jTextField1.getText().isEmpty()) {
        
        Thread thread = new Thread(new Runnable() {

            public void run() {
                
                while(true) {
                    try {
                        FlightChange.check();
                    } catch (Exception ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    try {
                        //Time Interval
                        if (jComboBox1.getSelectedItem().toString().equals("minutes")) {
                        Thread.sleep(Integer.parseInt(jTextField1.getText()) * 60 * 1000);}
                        if (jComboBox1.getSelectedItem().toString().equals("hours")) {
                        Thread.sleep(Integer.parseInt(jTextField1.getText()) * 3600 * 1000);}
                        else {
                            
                        }
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        FlightChange.check2();
                    } catch (Exception ex) {
                        Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                String doc1 = "/Users/GJKOfficial/NotiFlight/Downloaded/DownloadedSchedule.txt";
                String doc2 = "/Users/GJKOfficial/NotiFlight/Downloaded/DownloadedSchedule2.txt";
                
                try {
                    if (!FlightChange.checkEqual(doc1, doc2)) {
                        EmailNotification.Email();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Notify.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            });
            thread.start();        

        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notify().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
